config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'accounts'

  resources :users do
    resources :dramas
  end

  root 'dramas#index'
  get "dramas/update_all" => "dramas#update_all"

  devise_scope :user do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/drama.rb
require 'nokogiri'
require 'open-uri'
require 'uri'

class Drama < ActiveRecord::Base
	belongs_to :user

	validates :url, presence: :true, uniqueness: {:scope=>:user_id}, :url => true

	before_save :fetch_drama_info

	default_scope -> { order(created_at: :desc) }
	scope :titles, -> { select(:title).map(&:title) }

	def fetch_drama_info
			doc = Nokogiri::HTML(open(url))

			if doc.css('h3:nth-child(6)').text == 'List Episode'
				title = doc.at_css('h1').text
				last_ep_title = doc.css('#content-left li:nth-child(1) a').text
				subbed_img_url = doc.css('li:nth-child(1) .raw').attr('src').to_s
				subbed = subbed_img_url.include? "sub"
				broadcast_date = doc.css('li:nth-child(1) span').text
				poster = doc.css('.poster').attr('src').to_s
				drama_description = doc.css('.info p').text

				self.title = title
				self.img = poster
				self.description = drama_description
				self.subbed = subbed
				self.broadcasted_at = Date.strptime(broadcast_date, "%A, %m/%d/%Y")
				self.last_ep = last_ep_title.split('Episode')[-1].strip
				self.last_refresh = Time.now
			else
				errors.add(:url, "This url wouldn't work..")
			end

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :dramas, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dramas_controller.rb
require 'nokogiri'
require 'open-uri'

class DramasController < ApplicationController
  before_action :set_drama, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /dramas
  # GET /dramas.json
  def index
    if user_signed_in?
      @user = current_user
      @dramas = current_user.dramas.all
      @titles = current_user.dramas.titles
    end
  end

  # GET /dramas/1
  # GET /dramas/1.json
  def show
    @user = current_user
  end

  # GET /dramas/new
  def new
    @user = current_user
    @drama = @user.dramas.new
  end

  # GET /dramas/1/edit
  def edit
    @user = current_user
  end

  # POST /dramas
  # POST /dramas.json
  def create
    @user = current_user
    @drama = current_user.dramas.new(drama_params)

    respond_to do |format|
      if @drama.save
        format.html { redirect_to user_drama_path(user_id: current_user.id, id: @drama.id), notice: 'Drama was successfully created.' }
        format.json { render :show, status: :created, location: @drama }
      else
        format.html { render :new }
        format.json { render json: @drama.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /dramas/1
  # PATCH/PUT /dramas/1.json
  def update
    respond_to do |format|
      if @drama.update(drama_params)
        format.html { redirect_to user_drama_path(user_id: current_user.id, id: @drama.id), notice: 'Drama was successfully updated.' }
        format.json { render :show, status: :ok, location: @drama }
      else
        format.html { render :edit }
        format.json { render json: @drama.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_all
    @dramas = current_user.dramas.all
    Drama.all.each do |drama|
      drama.fetch_drama_info
      drama.save
    end
    respond_to do |format|
      format.js
    end
  end

  # DELETE /dramas/1
  # DELETE /dramas/1.json
  def destroy
    @drama.destroy
    respond_to do |format|
      format.html { redirect_to user_dramas_url(current_user), notice: 'Drama was successfully deleted.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drama
      @drama = current_user.dramas.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drama_params
      params.require(:drama).permit(:url, :title, :subbed, :broadcasted_at, :description, :img)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to user_dramas_path(user_id: current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg, class: "chip red darken-1 error_chip z-depth-2 animated flipInX") }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dramas/_drama_card.html.erb
<% @dramas.each do |drama| %>
<div
  class="card drama z-depth-3 animated fadeIn"
  id="<%= drama.id %>"
  style="
                background: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url(<%= drama.img %>) no-repeat;
                background-size: cover;
                ">
  <div class="card-content">
    <p class="card-title"><%= link_to truncate(drama.title, length: 30, separator: ' '), user_drama_path(user_id: current_user.id, id: drama.id) %></p>

    <div id="<%= drama.id %>-info-chips">
      <%= render partial: 'info_chips_partial',  locals: { drama: drama } %>
    </div>

    <p class="drama-description"><%= truncate(drama.description, length: 150, separator: ' ') %>
      <p>
      </div>
      <div class="card-action index">
        <a href=<%= drama.url %> target="_blank">Watch now</a>
        <%= link_to 'Delete', user_drama_path(user_id: current_user.id, id: drama.id), method: :delete, remote: true %>
      </div>
  </div>
<% end %>

app/views/dramas/_floating_btns.html.erb
<div class="fixed-action-btn hoverable horizontal animated flipInX" style="bottom: 45px; right: 24px;">
				    <a class="btn-floating btn-large red">
				      <i class="large mdi-navigation-menu"></i>
				    </a>
				    <ul>
				      <li><a class="btn-floating blue tooltipped" data-position="top" data-delay="50" data-tooltip="Add new drama" href="<%= new_user_drama_path(@user) %>"><i class="material-icons">add</i></a></li>
				      <li><a class="btn-floating green tooltipped" data-position="top" data-delay="50" data-tooltip="Update all" href="#" id="up_all_btn"><i class="material-icons">loop</i></a></li>
				    </ul>
</div>

app/views/dramas/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text footer-title">Drama Scraper</h5>
      <p class="grey-text text-lighten-4">Get information about all new episodes with just one click.</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">Paste links from:</h5>
      <ul>
        <li>
          <a class="grey-text text-lighten-3" href="http://myasiantv.se/">MyAsianTv</a>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div id="copy" class="container">
    © 2016 Paweł Targoński
  </div>
</div>

app/views/dramas/_form.html.erb
<%= form_for([@user, @drama]) do |f| %>
  <% if @drama.errors.any? %>
    <div id="error_explanation">
      <p>
      <% @drama.errors.full_messages.each do |message| %>
        <span class="chip red darken-1 error_chip z-depth-2 animated flipInX"><%= message %></span>
      <% end %>
      </p>
      <br>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, placeholder: "paste url from myasiantv.se" %>
  </div>

  <div class="actions">
    <%= link_to 'Cancel', user_dramas_path(@user), class: 'waves-effect waves-light btn' %>
    <%= f.submit 'Submit', class: 'waves-effect waves-light btn' %>
  </div>
<% end %>

app/views/dramas/_info_chips_partial.html.erb
<div class="chip light-green accent-3 z-depth-1 title-chip">
  <%= drama.last_ep %>
  <i class="material-icons">theaters</i>
</div>
<div class="chip light-green accent-2 z-depth-1 last_up_chip">
  <%= local_time_ago(drama.last_refresh) %>
  <i class="material-icons">loop</i>
</div>
<% if drama.subbed? %>
<div class="chip light-green accent-1 z-depth-1">
  Subbed!
  <i class="material-icons">done</i>
</div>
<% else %>
<div class="chip red darken-1 z-depth-1">
  Raw..
  <i class="material-icons">error_outline</i>
</div>
<% end %>
<br>
<br>

app/views/dramas/_navbar.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <a href="<%= root_path %>" class="brand-logo center">Drama Scraper</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse">
        <i class="material-icons">menu</i>
      </a>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li>
            <a href="/"><%= current_user.email %></a>
          </li>
          <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
      <ul class="side-nav z-depth-5" id="mobile-demo">
        <% if user_signed_in? %>
        <li>
          <div class="chip light-green accent-3 user-chip-mobile">
            <%= current_user.email %>
            <i class="material-icons">perm_identity</i>
          </div>
        </li>
        <li><%= link_to 'Log Out', destroy_user_session_path %></li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/dramas/_summary_card.html.erb
<div class="card-panel z-depth-3 blue darken-2 drama" id="summary-card">
          <span class="white-text">
          <h3 class="flow-text">Hi <%= @user.email %>!</h3>
          <% if @dramas.any? %>
            <p class="flow-text">Currently you are watching <%= @titles.to_sentence %></p>
          <% else %>
            <p class="flow-text">You can start by pasting some URL.</p>
          <% end %>
          </span>
 </div>

app/views/dramas/destroy.js.erb
$('#<%= @drama.id %>').fadeOut();
$('#<%= @drama.id %>').remove();
$('#dramas').masonry('reload');

app/views/dramas/edit.html.erb
<h1>Editing Drama</h1>

<%= render 'form' %>

app/views/dramas/index.html.erb
<div class="row">
	<div class="col s12">
			<div id="dramas" class="transitions-enabled">
				<%= render 'drama_card' %>
			</div>
		<%= render 'floating_btns' %>
	</div>
</div>

app/views/dramas/new.html.erb
<div class="card-panel">
	<h2 class="flow-text">New Drama</h2>
	<br>
	<p>Currently you can only paste urls from <strong>http://myasiantv.se/</strong>.</p>
	<p>Following formats will be accepted:</p>
	<blockquote>
	      <p>http://myasiantv.se/movie/some-movie/</p>
	      <p>http://myasiantv.se/drama/some-drama/</p>
	</blockquote>
	<br>

	<%= render 'form' %>		
</div>

app/views/dramas/show.html.erb
<style media="screen">
body {
    position: absolute;
    top: 0; bottom: 0; left: 0; right: 0;
    height: 100%;
}
body:before {
    content: "";
    position: absolute;
    height: 20%; width: 20%;
    background: url(<%= @drama.img %>);
    background-size: cover;
    z-index: -1;
    -webkit-transform: scale(5);
        -ms-transform: scale(5);
            transform: scale(5);
    -webkit-transform-origin: top left;
        -ms-transform-origin: top left;
            transform-origin: top left;
    filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feGaussianBlur stdDeviation="2" /></filter></svg>#filter');
    -webkit-filter: blur(2px);
            filter: blur(2px);
    filter: progid:DXImageTransform.Microsoft.Blur(pixelradius=2);
}
</style>

<div class="card show animated fadeIn">
<h4 class="flow-text">
  <%= @drama.title %>
</h4>
    <div class="chip light-green accent-3 z-depth-1">
                  <%= @drama.last_ep.split('Episode')[-1].strip %>
              <i class="material-icons">theaters</i>
              </div>
            <% if @drama.subbed? %>
              <div class="chip light-green accent-3 z-depth-1">
                  Subbed!
              <i class="material-icons">done</i>
              </div>
              <% else %>
              <div class="chip red darken-1 z-depth-1">
                  Raw..
              <i class="material-icons">error_outline</i>
              </div>
            <% end %>
            <br>
<p>
  Last episode was broadcast <strong><%= @drama.broadcasted_at.stamp("Sunday, May 1, 2000") %></strong>, so it was <strong><%= time_ago_in_words @drama.broadcasted_at %></strong> ago.
</p>

<p class="flow-text">
  <%= @drama.description %>
</p>
<div class="card-action">
        <a href=<%= @drama.url %> target="_blank" >Watch now</a>
        <%= link_to 'Back', user_dramas_path(current_user) %>
</div>
</div>

app/views/dramas/update_all.js.erb
<% @dramas.each do |drama| %>
  $("#<%= drama.id %>-info-chips").fadeOut("slow");
  $("#<%= drama.id %>-info-chips").replaceWith("<%= j render partial: "info_chips_partial", locals: { drama: drama } %>").fadeIn("slow");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drama Scraper</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="theme-color" content="#262626">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  </head>
  <body>

    <header>
      <%= render '/dramas/navbar' %>
    </header>

    <main>

      <% if notice.present? %>
  			<p id="notice" class="chip animated fadeIn"><%= notice %><i class="material-icons">close</i></p>
  		<% end %>

      <% if alert %>
        <p id="alert" class="alert chip red darken-1 error_chip z-depth-2 animated flipInX"><%= alert %></p>
      <% end %>

      <div class="container">
          <%= yield %>
      </div>
    </main>

    <footer class="page-footer">
      <%= render '/dramas/footer' %>
    </footer>

    <div class="preloader-wrapper big active">
      <div class="spinner-layer spinner-blue-only">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div>
        <div class="gap-patch">
          <div class="circle"></div>
        </div>
        <div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
    </div>

    <div class="preloader-overlay"></div>

  </body>
</html>

app/views/welcome/index.html.erb
<div class="welcome-wrapper">
  <a class="waves-effect waves-light btn-large" href="<%= new_user_session_path %>"><i class="material-icons right">play_arrow</i>Log in</a>
</div>